export enum TournamentResponseMessages {

    ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN",
    ERR_INTERNAL_SERVER = "ERR_INTERNAL_SERVER",
    ERR_TOURNAMENT_NAME_REQUIRED = "ERR_TOURNAMENT_NAME_REQUIRED",
    ERR_TOURNAMENT_NAME_EMPTY = "ERR_TOURNAMENT_NAME_EMPTY",
    ERR_TOURNAMENT_NAME_INVALID_CHARS = "ERR_TOURNAMENT_NAME_INVALID_CHARS",
    ERR_TOURNAMENT_NAME_EXISTS = "ERR_TOURNAMENT_NAME_EXISTS",
    ERR_PARTICIPANT_ALREADY_IN_TOURNAMENT = "ERR_PARTICIPANT_ALREADY_IN_TOURNAMENT",
    ERR_TOURNAMENT_NAME_TOO_LONG = "ERR_TOURNAMENT_NAME_TOO_LONG",
    SUCCESS_TOURNAMENT_CREATED = "SUCCESS_TOURNAMENT_CREATED",
    ERR_MAX_10_PARTICIPANTS = "ERR_MAX_10_PARTICIPANTS",
    ERR_TOURNAMENT_NOT_JOINABLE = "ERR_TOURNAMENT_NOT_JOINABLE",
    ERR_PARTICIPANT_ALREADY_JOINED = "ERR_PARTICIPANT_ALREADY_JOINED",
    ERR_TOURNAMENT_NOT_FOUND = "ERR_TOURNAMENT_NOT_FOUND",
    ERR_PARTICIPANT_NOT_FOUND = "ERR_PARTICIPANT_NOT_FOUND",
    ERR_ADMIN_CANNOT_LEAVE = "ERR_ADMIN_CANNOT_LEAVE",
    ERR_NO_ONGOING_ROUNDS = "ERR_NO_ONGOING_ROUNDS",
    ERR_NO_COMPLETED_ROUNDS = "ERR_NO_COMPLETED_ROUNDS",
    ERR_TOURNAMENT_NOT_DELETABLE = "ERR_TOURNAMENT_NOT_DELETABLE",
    ERR_ONLY_ADMIN_CAN_DELETE = "ERR_ONLY_ADMIN_CAN_DELETE",
    ERR_TOURNAMENT_NOT_FOUND_UUID = "ERR_TOURNAMENT_NOT_FOUND_UUID",
    ERR_ONLY_ADMIN_CAN_START = "ERR_ONLY_ADMIN_CAN_START",
    ERR_TOURNAMENT_NOT_STARTABLE = "ERR_TOURNAMENT_NOT_STARTABLE",
    ERR_NOT_ENOUGH_PARTICIPANTS = "ERR_NOT_ENOUGH_PARTICIPANTS",
    ERR_MATCH_NOT_JOINABLE = "ERR_MATCH_NOT_JOINABLE",
    ERR_PARTICIPANT_DISCONNECTED = "ERR_PARTICIPANT_DISCONNECTED",
    SUCCESS_WINNER_ADDED = "SUCCESS_WINNER_ADDED",
    SUCCESS_TOURNAMENT_COMPLETED = "SUCCESS_TOURNAMENT_COMPLETED",
    SUCCESS_NEXT_ROUND_STARTED = "SUCCESS_NEXT_ROUND_STARTED",
    ERR_TOURNAMENT_NOT_MATCH_JOINABLE = "ERR_TOURNAMENT_NOT_MATCH_JOINABLE",
    ERR_ROUND_NOT_FOUND = "ERR_ROUND_NOT_FOUND",
    ERR_ROUND_COMPLETED = "ERR_ROUND_COMPLETED",
    ERR_MATCH_STATE_NOT_JOINABLE = "ERR_MATCH_STATE_NOT_JOINABLE",
    ERR_MATCH_STATE_NOT_LEAVABLE = "ERR_MATCH_STATE_NOT_LEAVABLE",
    ERR_PARTICIPANT_NOT_IN_TOURNAMENT = "ERR_PARTICIPANT_NOT_IN_TOURNAMENT",
    ERR_PARTICIPANT_ALREADY_IN_MATCH = "ERR_PARTICIPANT_ALREADY_IN_MATCH",
    ERR_PARTICIPANT_ALREADY_DISCONNECTED = "ERR_PARTICIPANT_ALREADY_DISCONNECTED",
    SUCCESS_PARTICIPANT_JOINED = "SUCCESS_PARTICIPANT_JOINED",
    SUCCESS_PARTICIPANT_LEFT = "SUCCESS_PARTICIPANT_LEFT",
    SUCCESS_TOURNAMENT_DELETED = "SUCCESS_TOURNAMENT_DELETED",
    SUCCESS_PARTICIPANTS_RETRIEVED = "SUCCESS_PARTICIPANTS_RETRIEVED",
    SUCCESS_TOURNAMENT_RETRIEVED_UUID = "SUCCESS_TOURNAMENT_RETRIEVED_UUID",
    SUCCESS_TOURNAMENT_STARTED = "SUCCESS_TOURNAMENT_STARTED",
    SUCCESS_PARTICIPANT_JOINED_MATCH = "SUCCESS_PARTICIPANT_JOINED_MATCH",
    SUCCESS_PARTICIPANT_LEAVED_MATCH = "SUCCESS_PARTICIPANT_LEAVED_MATCH",
    ERR_PARTICIPANT_NOT_FOUND_ROUND = "ERR_PARTICIPANT_NOT_FOUND_ROUND",
    ERR_TOURNAMENT_NOT_ADD_WINNERS = "ERR_TOURNAMENT_NOT_ADD_WINNERS",
    ERR_NO_ROUNDS_FOUND = "ERR_NO_ROUNDS_FOUND",
    ERR_ROUND_NUMBER_MISMATCH = "ERR_ROUND_NUMBER_MISMATCH",
    ERR_WINNER_NOT_IN_MATCHES = "ERR_WINNER_NOT_IN_MATCHES",
    ERR_RIVAL_ALREADY_WON = "ERR_RIVAL_ALREADY_WON",
    ERR_WINNER_ALREADY_ADDED = "ERR_WINNER_ALREADY_ADDED",

}

export interface IUser {
	id: number;
	username: string;
	name: string;
	surname: string;
	email: string;
	language: string;
	avatar: string;
}